### ISSUE TITLE
[WARNING] SecureHandlebars: {{> photo}} is in non-DATA State!

### ISSUE THREAD

**Issue by jeremyruppel** [yahoo/express-secure-handlebars#17]
What does it mean for a partial to be in a DATA State? Can this warning be more clear?

**Comment by neraliu** [comment]
Right now, secure-handlebars analyze each Handlebars template files separately and add secure filters based on the context accordingly, it implies that each template file starts with the same initial context, which is the DATA state, for context analysis. so we warn the developer if it is not the case.
reference: https://github.com/yahoo/secure-handlebars#known-limitations--issues

FYI, Based on the HTML5 specification, the initial state is called `DATA state`. In order to mak the warning more clear, we will change the wording to `HTML context` in our warning message in next release.

**Comment by neraliu** [comment]
PR for this - https://github.com/yahoo/secure-handlebars/pull/114

**Comment by neraliu** [comment]
we will support the partial handling in non-HTML context, issue for this https://github.com/yahoo/secure-handlebars/issues/124

**Comment by neraliu** [comment]
secure-handlebars@1.1.1 has included this fix
